xbox_controller:
  config:
    normalised: true
    debug: false
    device: /dev/input/js0
    deadzone: 4000
    button_names:
      0: BTN_A
      1: BTN_B
      2: BTN_X
      3: BTN_Y
      4: BTN_TL
      5: BTN_TR
      6: BTN_SELECT
      7: BTN_START
      8: BTN_MODE
      9: BTN_THUMBL
      10: BTN_THUMBR
      11: KEY_RECORD
    axis_names:
      0: ABS_X
      1: ABS_Y
      2: ABS_Z
      3: ABS_RZ
      4: ABS_RX
      5: ABS_RY
      6: ABS_HAT0X
      7: ABS_HAT0Y
    axis_max: 32767.0
    axis_min: -32767.0
  class: XboxController
