controller_handler:
  config:
    debug: false
    modifier_buttons:
    - BTN_TL
    - BTN_TR
    mapping:
      default:
        BTN_TL:
          actions:
          - topic: ''
            args: {}
        BTN_TR:
          actions:
          - topic: ''
            args: {}
        BTN_SELECT:
          actions:
          - topic: record/stop
            args: {}
        BTN_START:
          actions:
          - topic: record/start
            args: {}
        KEY_RECORD:
          actions:
          - topic: ''
            args: {}
        BTN_MODE:
          actions:
          - topic: ''
            args: {}
        ABS_HAT0X:
          actions:
          - topic: ''
            args: {}
        ABS_HAT0Y:
          actions:
          - topic: ''
            args: {}
        BTN_A:
          actions:
          - topic: tts
            args:
              msg: Test Default
        BTN_X:
          actions:
          - topic: eye/blink
            args: {}
        BTN_Y:
          actions:
          - topic: gpio/laser/toggle
            args: {}
        BTN_B:
          actions:
          - topic: vision/toggle
            args: {}
        ABS_RX:
          actions:
          - topic: servo:neck_pan:mv
            args: {}
            modifier:
              scale: 50
        ABS_RZ:
          actions:
          - topic: servo:neck_tilt:mv
            args: {}
            modifier:
              scale: -50
          - topic: servo:neck_tilt2:mv
            args: {}
            modifier:
              scale: 50
        ABS_RY:
          start: -1.0
          actions:
          - topic: servo:leg_r_ankle:mv
            args: {}
            modifier:
              scale: -50
        ABS_Z:
          start: -1.0
          actions:
          - topic: servo:leg_l_ankle:mv
            args: {}
            modifier:
              scale: -50
        ABS_X:
          actions:
          - topic: eye/move
            args:
              axis: y
            modifier:
              mapping:
              - 0
              - 240
        ABS_Y:
          actions:
          - topic: eye/move
            args:
              axis: x
            modifier:
              mapping:
              - 240
              - 0
      BTN_TL:
        BTN_X:
          actions:
          - topic: servo:neck_pan:mv
            args:
              delta: -50
        BTN_Y:
          actions:
          - topic: servo:neck_tilt:mv
            args:
              delta: -50
          - topic: servo:neck_tilt2:mv
            args:
              delta: 50
        BTN_B:
          actions:
          - topic: servo:neck_pan:mv
            args:
              delta: 50
        BTN_A:
          actions:
          - topic: servo:neck_tilt:mv
            args:
              delta: 50
          - topic: servo:neck_tilt2:mv
            args:
              delta: -50
      BTN_TR:
        BTN_X:
          actions:
          - topic: servo:neck_tilt:mv
            args:
              delta: 50
        BTN_Y:
          actions:
          - topic: servo:neck_tilt:mv
            args:
              delta: -50
        BTN_B:
          actions:
          - topic: servo:neck_tilt2:mv
            args:
              delta: 50
        BTN_A:
          actions:
          - topic: servo:neck_tilt2:mv
            args:
              delta: -50
        ABS_HAT0Y:
          actions:
          - topic: servo:neck_tilt:mvabs
            args:
              position: 511
          - topic: servo:neck_tilt2:mvabs
            args:
              position: 511
        ABS_X:
          actions:
          - topic: servo:leg_l_ankle:mv
            modifier:
              scale: 50
          - topic: servo:leg_r_ankle:mv
            modifier:
              scale: -50
          - topic: servo:leg_l_knee:mv
            modifier:
              scale: 50
          - topic: servo:leg_r_knee:mv
            modifier:
              scale: -50
          - topic: servo:leg_l_hip:mv
            modifier:
              scale: 50
          - topic: servo:leg_r_hip:mv
            modifier:
              scale: -50
  class: ControllerHandler
