i2c_servo:
  enabled: false
  path: modules.i2c_servo.I2CServo
  config:
    test_on_boot: false
    servo_count: 16
  dependencies:
    unix:
      - python3-smbus
    python:
      - adafruit-circuitpython-servokit