piservo:
  enabled: true
  path: modules.actuators.piservo.PiServo
  instances:
    - name: "ear"
      id: 0
      pin: 12 
      range: [-40, 40]
      start: 0
  dependencies:
    python:
      - gpiozero
