name: Run Tests

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install unittest-xml-reporting

    - name: Run tests
      run: |
        mkdir -p test-reports
        python -m unittest discover -s tests -p "test_*.py" --buffer | tee test-reports/results.txt
      continue-on-error: true

    - name: Publish test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-reports/

    - name: Comment on PR
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const results = fs.readFileSync('test-reports/results.txt', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Test results:\n\n\`\`\`\n${results}\n\`\`\``
          });