name: Python Unittest on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unittests
        id: run-tests
        run: |
          python -m unittest discover -s tests -p 'test_*.py' > results.log 2>&1 || echo "TESTS_FAILED=true" >> $GITHUB_ENV

      - name: Output test results
        if: env.TESTS_FAILED == 'true'
        run: cat results.log

      - name: Comment on PR if tests fail
        if: env.TESTS_FAILED == 'true'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ❌ Unit tests failed:
            ```
            $(cat results.log)
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      pull-requests: write
      contents: read
